spring.application.name=bank-xyz

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/bank_xyz?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false