spring.application.name=bank-xyz-bff

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/bank_xyz?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SSL / HTTPS
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=bankxyz2024
server.ssl.key-alias=bank-xyz
server.ssl.enabled=true

# Usuarios BFF por canal
bff.security.web.user=web_user
bff.security.web.password=web_pass_2024
bff.security.mobile.user=mobile_user
bff.security.mobile.password=mobile_pass_2024
bff.security.atm.user=atm_user
bff.security.atm.password=atm_pass_2024